/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : pin_mux.h
**     Project     : USB-KW40
**     Processor   : MKW40Z160VHT4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-10, 14:05, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         GPIO                - void pin_mux_GPIO(uint32_t instance);
**         I2C                 - void pin_mux_I2C(uint32_t instance);
**         TPM                 - void pin_mux_TPM(uint32_t instance);
**         RTC                 - void pin_mux_RTC(uint32_t instance);
**         SPI                 - void pin_mux_SPI(uint32_t instance);
**         LPUART              - void pin_mux_LPUART(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.h
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

#ifndef pin_mux_H_
#define pin_mux_H_

/* MODULE pin_mux. */

/*!
 * @brief CMP method sets registers according routing settings. Call
 *         this method code to route desired pins into CMP0 periphery.
 * @param instance - CMP instance number (0 is expected)
 */
void configure_cmp_pins(uint32_t instance);
/*!
 * @brief GPIO method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         GPIOA, GPIOB, GPIOC
 *         peripherals.
 * @param instance - GPIO instance number 0..2
 */
void configure_gpio_pins(uint32_t instance);
/*!
 * @brief I2C method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         I2C0, I2C1
 *         peripherals.
 * @param instance - I2C instance number 0..1
 */
void configure_i2c_pins(uint32_t instance);
/*!
 * @brief LLWU method sets registers according routing settings. Call
 *         this method code to route desired pins into LLWU periphery.
 * @param instance - LLWU instance number (0 is expected)
 */
void configure_llwu_pins(uint32_t instance);
/*!
 * @brief LPUART method sets registers according routing settings. Call
 *         this method code to route desired pins into LPUART0 periphery.
 * @param instance - LPUART instance number (0 is expected)
 */
void configure_lpuart_pins(uint32_t instance);
/*!
 * @brief SPI method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         SPI0, SPI1
 *         peripherals.
 * @param instance - SPI instance number 0..1
 */
void configure_spi_pins(uint32_t instance);
/*!
 * @brief TPM method sets registers according routing settings. Call
 *         this method code to route desired pins into:
 *         TPM0, TPM1, TPM2
 *         peripherals.
 * @param instance - TPM instance number 0..2
 */
void configure_tpm_pins(uint32_t instance);

/* END pin_mux. */
#endif /* #ifndef __pin_mux_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
